apiVersion: v1
kind: Service
metadata:
  name: ci-cd-practice-service
  labels:
    app: ci-cd-practice
spec:
  type: LoadBalancer
  selector:
    app: ci-cd-practice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
